covidnewstracker/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('news.urls')),
    path('',include('users.urls')),
    path('', include('django.contrib.auth.urls')),
]

news/urls.py
from django.urls import path, include
from . import views 
# from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('newsForm', views.news_scrape, name='news-form'),
    path('nsearch',views.search, name ='nsearch'),
    path('allNews',views.all_news, name ='all-news'),
    path('filterByDate',views.filter_by_date, name ='filter-by-date'),
    path('<slug:slug>', views.news_detail, name="news-detail"),
]

news/models.py
from django.db import models
from uuid import uuid4

class News(models.Model):
    date_created = models.DateField(auto_now=True)
    date_published = models.DateField()
    author = models.CharField(max_length=255)
    source = models.CharField(max_length=255)
    title = models.CharField(max_length=255, unique=True)
    url = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, default=uuid4)
    excerpt = models.TextField()
    content = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

news/forms.py
from django import forms

SITES = (
    ('nepalitimes', 'Nepali Times'),
    ('newsapi', 'News API')
)

class NewsForm(forms.Form):
    source = forms.ChoiceField(choices=SITES)

news/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from .forms import NewsForm
from .models import News
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime
from django.contrib import messages
from scrapy.crawler import CrawlerProcess
from scrapy.crawler import CrawlerRunner
from scrapy.utils.project import get_project_settings
import os
from scrapyd_api import ScrapydAPI
from scrapy.settings import Settings
from crawling.crawling.spiders import newsapi
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required
from django.core import management



def is_scraper(user):
    return user.groups.filter(name='Scraper').exists()

@login_required(login_url='/login')
@user_passes_test(is_scraper, login_url='/login')        
def news_scrape(request):
    if request.method == 'POST':
        forms = NewsForm(request.POST)
        if forms.is_valid():
            if form.cleaned_data.get('source') == 'newsapi':
                management.call_command('crawl_newsapi')
            else:
                management.call_command('crawl_nepalitimes')
            messages.success(request, f'News scrapped successfully!')
            return redirect('all-news')
    else:
        forms = NewsForm()
    context = {'forms': forms }
    return render(request, 'news/news_form.html',context)

def dashboard(request):
    total_articles = News.objects.count()
    no_of_sources = News.objects.values('source').distinct().count()
    no_of_authors = News.objects.values('author').distinct().count()
    labels = []
    datas = []

    queryset = News.objects.values('source').distinct()
    for news in queryset:
        labels.append(news['source'])
        datas.append(News.objects.filter(source=news['source']).count())
    context= {
        'total_articles':total_articles,
        'no_of_sources':no_of_sources,
        'no_of_authors': no_of_authors,
        'news':news,
        'labels': labels,
        'datas': datas
    }
    print(context)
    return render(request, 'news/dashboard.html',context)


@login_required(login_url='/login')
def search(request):

    news_ = News.objects.order_by('?') # to get unordered/shuffled list

    if request.method == 'GET':
        query= request.GET.get('search')

        if query is not None:
            lookups= Q(title__icontains=query) | Q(excerpt__icontains=query) | Q(content__icontains=query) | Q(author__icontains=query)

            results= News.objects.filter(lookups).distinct()

            page = request.GET.get('page', 1)
            paginator = Paginator(results, 4)
            try:
                results = paginator.page(page)
            except PageNotAnInteger:
                results = paginator.page(1)
            except EmptyPage:
                results = paginator.page(paginator.num_pages)

            context={
                'results': results,
            }
            print(results)
            return render(request, 'news/search_result.html', context)

        else:
            return redirect('all-news')

    else:
        return redirect('all-news')

@login_required(login_url='/login')
def all_news (request):
    news = News.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(news, 4)
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)
    context = {
        "news":news
    }
    return render(request,'news/all_news.html',context)

@login_required(login_url='/login')
def news_detail(request, slug): 

    news = News.objects.get(slug=slug) # returns only one object
    
    context = {
        'news': news
    }
    return render(request, 'news/detail_news.html', context)

@login_required(login_url='/login')
def filter_by_date(request):

    news = News.objects.order_by('?')

    if request.method == 'GET':
        query= request.GET.get('filterByDate',False)

        if query is not None:
            if query == 'today':
                today = datetime.datetime.today().strftime('%Y-%m-%d')
                news = News.objects.filter(date_published=today)
            elif query == 'latest':
                news = News.objects.order_by('-date_published')
            else:
                news = News.objects.order_by('date_published')
            page = request.GET.get('page', 1)
            paginator = Paginator(news, 4)
            try:
                news = paginator.page(page)
            except PageNotAnInteger:
                news = paginator.page(1)
            except EmptyPage:
                news = paginator.page(paginator.num_pages)
            print(news)
            context={
                'news': news
            }
            return render(request, 'news/all_news.html', context)

        else:
            return redirect('all-news')

    else:
        return redirect('all-news')

news/templates/news/all_news.html
{% extends "news/base.html" %}
{% load static %}
{% block content%}

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <h5>Filter</h5>
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'filter-by-date' %}">
                <h6>By Date</h6>
                <div class="input-group">
                    <select class="form-control bg-light border-0 small" name='filterByDate' onchange="this.form.submit()">
                        <option value='today'>Today</option>
                        <option value='latest'>Latest</option>
                        <option value='oldest'>Oldest</option>
                    </select>
                </div>
            </form>
        </div>
        <div class="col-md-8">
        {% for news in news%}
            <div class="masonry-box" style="width: 100% !important">
                <div class="blog-box" id="{{news.slug}}" data-heading="{{news.title}}" 
                 data-published="{{news.date_published}}" data-news="{{news.content}}" 
                data-author="{{news.author}}"
                data-toggle="modal" data-target="">
            
                <div class="blog-meta">
                    <h4><a href="/news/{{news.slug}}" title="">{{news.title}}</a></h4>
                    <p class="text-justify">{{news.excerpt}}</p>
                    <small>{{news.author}}</small>
                    <small>{{news.date_published}}</small>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>

<nav>
    <ul class="pagination justify-content-center">
        <li class="page-item {% if not news.has_previous %} disabled {% endif %}">
            <a class="page-link" href="{% if news.has_previous %} ?page={{ news.previous_page_number }}{% endif %} ">Previous</a>
        </li>
  
        {% if news.number|add:'-1' > 1 %}
            <li class="page-item disabled"><a class="page-link">&hellip;</a></li>
        {% endif %}
  
        {% for i in news.paginator.page_range %}
            {% if news.number == i %}
                <li class="active page-item disabled"><a class="page-link" href="#">{{ i }}</a></li>
            {% elif i > news.number|add:'-2' and i < news.number|add:'2' %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
  
        {% if news.paginator.num_pages > news.number|add:'1' %}
            <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
        {% endif %}
  
        <li class="page-item {% if not news.has_next %} disabled {% endif %}">
            <a class="page-link" href="{% if news.has_next %} ?page={{ news.next_page_number }} {% endif %}">Next</a>
        </li>
    </ul>
  </nav>  


{% endblock %}

news/templates/news/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
    crossorigin="anonymous" />

</head>
<body>
  {% block scripts %}
  {% endblock scripts %}
  <nav class="navbar navbar-expand-sm bg-light">
    <ul class="navbar-nav">
        
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard' %}">Dashboard {{user}}</a>
        </li>
        {% if perms.news.add_news %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'news-form' %}">Scrape</a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'all-news' %}">All News</a>
        </li>
        <li class="nav-item">
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'nsearch' %}">
                <div class="input-group">
                    <input class="form-control bg-light border-0 small" type="search" name="search" placeholder="Search For.." aria-label="Search"/>
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                        <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/register">Register</a>
        </li>
        {% endif %}

    </ul>
</nav>
  <div class="container">
    
    {% block content %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
                {{message}}
        </div>
        {% endfor %}
    {% endif %}
    
    {% endblock %}
  </div>
</body>
</html>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

news/templates/news/dashboard.html
{% extends 'news/base.html' %}

{% load crispy_forms_tags %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>
var config = {
      type: 'pie',
      data: {
        datasets: [{
            data: {{datas|safe }},
            backgroundColor: [
                'rgba(255, 99, 132, 1)', 
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(200, 201, 150, 1)',
                'rgba(150, 120, 170, 1)',
                'rgba(253, 012, 149, 1)',
                'rgba(102, 093, 240, 1)',
                'rgba(236, 125, 240, 1)',
                'rgba(085, 093, 045, 1)',
                'rgba(005, 125, 240, 1)',
                'rgba(125, 093, 365, 1)',
                // '#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3'
            ],
            label: 'Number of Post Per Author'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

</script>
{% endblock scripts %}

{% block content %}
    {% if perms.news.view_news %}
          <div class="row">
            <div class="col-lg-6 col-xl-3 mb-4">
                <div class="card bg-primary text-white h-100">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="me-3">
                                <div class="text-white-75 small">Number of News</div>
                                <div class="text-lg fw-bold">{{total_articles}}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-3 mb-4">
                <div class="card bg-success text-white h-100">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="me-3">
                                <div class="text-white-75 small">Number of Sources</div>
                                <div class="text-lg fw-bold">{{no_of_sources}}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-3 mb-4">
                <div class="card bg-warning text-white h-100">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="me-3">
                                <div class="text-white-75 small">Number of Authors</div>
                                <div class="text-lg fw-bold">{{no_of_authors}}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="container" style="width: 75%;">
            <h5>No of News Per Source</h5>
            <canvas id="pie-chart"></canvas>
          </div>
    
    {% endif %}
          
{% endblock %}

news/templates/news/detail_news.html
{% extends 'news/base.html' %}  
<title>{{news.Title}}</title>

{%block content%}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8  mt-4">
      <div class="px-4">
        <div id="news">
            <h4 class="pt-4">{{news.title}}</h4>
            <i class="fas fa-envelope mr-2"></i>
            <span> {{news.date_published}}</span>
            <i class="fas fa-user ml-4 mr-2"></i>
            <span> {{news.author}}</span>
            <br>
            <hr />
            <p class="text-justify" id="single-news-content">
            {{news.content}}
            </p>
        </div>
      </div>
</div>

{% endblock %}

news/templates/news/news_form.html
{% extends 'news/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    {% if perms.news.add_news %}
    <h5>News Scrapping! Please Select a Source To Scrape!</h5>
        <form method="post">
            {% csrf_token %}
            {{ forms|crispy }}
            <button type="submit" class="btn btn-primary">Scrape</button>
        </form>
    {% endif %}
    
{% endblock %}

news/templates/news/search_result.html
{% extends "news/base.html" %}
{% load static %}
{% block content %}

<div class="container">

    <br/>

    {% if request.GET.q != '' %}
    {% if results %}
    <div class="row">
        <div class="col-lg-9">
            <div class="blog-list clearfix">
                <div class="section-title">
                    <h5>Results for News <b>{{ request.GET.q }}</b></h5>
                </div>
                {% for result in results%}
                <div class="blog-box row " id="{{result.slug}}" data-title="{{result.title}}"
                     data-published="{{result.date_published}}"
                    data-news="{{result.content}}" data-author="{{result.author}}" data-toggle="modal"
                    data-target="">
                    <div class="col-md-4">

                    </div>
                    <div class="blog-meta big-meta col-md-8">
                        <h4><a href="/news/{{result.slug}}" title="">{{result.title}}</a>
                        </h4>
                        <p class="text-justify">{{result.excerpt}}</p>
                        <small>{{result.date_published}}</small>
                        <small>by {{result.author}}</a></small>
                    </div>
                </div>
                <hr class="invis">
                {% endfor %}
            </div>
            <hr class="invis">
            </div>

        <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item {% if not results.has_previous %} disabled {% endif %}">
                    <a class="page-link" href="{% if results.has_previous %} ?page={{ results.previous_page_number }}{% endif %} ">Previous</a>
                </li>
          
                {% if results.number|add:'-1' > 1 %}
                    <li class="page-item disabled"><a class="page-link">&hellip;</a></li>
                {% endif %}
          
                {% for i in results.paginator.page_range %}
                    {% if results.number == i %}
                        <li class="active page-item disabled"><a class="page-link" href="#">{{ i }}</a></li>
                    {% elif i > results.number|add:'-2' and i < results.number|add:'2' %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
          
                {% if results.paginator.num_pages > results.number|add:'1' %}
                    <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
                {% endif %}
          
                <li class="page-item {% if not results.has_next %} disabled {% endif %}">
                    <a class="page-link" href="{% if results.has_next %} ?page={{ results.next_page_number }} {% endif %}">Next</a>
                </li>
            </ul>
          </nav>  
        
    </div>
</div>

{% else %}
No search results for this query
{% endif %}
{% endif %}
{% endblock%}